env:
  PRE_BUILD_COMMAND: git config --global --add safe.directory /github/workspace

name: tests_coverage_jacoco

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - '**.github/workflows/**'

  pull_request:
    branches: ["develop"]
    paths-ignore:
      - "**.github/workflows/**"

  schedule:
    - cron: "0 0 1 * *" # Once a month

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy:
    environment:
      name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}
      url: https://mathildemrz.github.io/VIP-portal/
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Build Maven
        run: mvn clean install

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "coverage/target/site/jacoco-aggregate/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2



      ##### Added #####
      - name: Commit and Push to History Branch
        run: |
          git fetch
          git branch -a
          git checkout -- .
          git checkout -b history_reports origin/history_reports
          git config --global user.email "mathilde.marza2001@gmail.com"
          git config --global user.name "MathildeMrz"
          # git pull origin develop
          git add -f "coverage/target/site/jacoco-aggregate/"
          DATE=$(date +%Y-%m-%d-%H-%M-%S)
          mkdir -p history/"$DATE"
          cp -R "coverage/target/site/jacoco-aggregate/." history/"$DATE"/
          git add -f history/"$DATE"
          git commit -m "Update Jacoco HTML report"
          git push origin
          # git push develop history_reports

